### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by Woterlov** [Delurg/Reshalo#4]
- [x] Создание функции расчета неполных квадратных уравнений(первый тип)

- [x] Создание функции расчета неполных квадратных уравнений(второй тип)

- [x] Созданий функции расчета полных квадратных уравнений
